### ISSUE TITLE
TypeError: Cannot read property 'raw_author' of undefined on commit hook

### ISSUE THREAD

**Issue by m00t** [Strider-CD/strider-bitbucket#17]
When I push new branch, or merge this branch to staging, eveything works fine. 

When I try to push to master fast-forwarded merge from staging, I got this in logs:
```
2015-03-26T07:03:52.531Z - error: TypeError: Cannot read property 'raw_author' of undefined
    at postPayload (/usr/local/lib/node_modules/strider/node_modules/strider-bitbucket/lib/api.js:154:34)
    at Object.startCommitJob (/usr/local/lib/node_modules/strider/node_modules/strider-bitbucket/lib/api.js:182:14)
    at /usr/local/lib/node_modules/strider/node_modules/strider-bitbucket/webapp.js:187:11
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/strider/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/lib/node_modules/strider/node_modules/express/lib/router/route.js:110:13)
    at projectProvider (/usr/local/lib/node_modules/strider/lib/middleware.js:123:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/strider/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/lib/node_modules/strider/node_modules/express/lib/router/route.js:110:13)
    at Promise.<anonymous> (/usr/local/lib/node_modules/strider/lib/middleware.js:249:7)
    at Promise.<anonymous> (/usr/local/lib/node_modules/strider/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.EventEmitter.emit (events.js:95:17)
    at Promise.emit (/usr/local/lib/node_modules/strider/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/usr/local/lib/node_modules/strider/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Promise.resolve (/usr/local/lib/node_modules/strider/node_modules/mongoose/lib/promise.js:114:23)
    at Promise.<anonymous> (/usr/local/lib/node_modules/strider/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.EventEmitter.emit (events.js:95:17)
POST /<project/repo>/api/bitbucket/commit/<secret> 500 33.957 ms - -
```

**Comment by chevett** [comment]
I am having the same problem here.  I push to dev branch.  Then if it all looks good I push to master, but strider fails with the raw_author message.

**Comment by chevett** [comment]
This appears to be a bug with bitbucket.  The commits array from bitbucket is empty, so there is no way to tell strider what to build.

There appears to be a new webhooks api from bitbucket.  Perhaps that works correctly?

**Comment by svenvarkel** [comment]
I'm able to reproduce this error so that I make 2 commits and pushes to the same projects to different branches. It occurs after 2nd push.

I forked the repo and I'm providing a workaround.
