### ISSUE TITLE
Error while adding new Bitbucket project

### ISSUE THREAD

**Issue by svenvarkel** [Strider-CD/strider-bitbucket#32]
Strider fails when I want to add a new project from Bitbucket (Projects->My BB projects tab->Add). The following error appears in the log:

```
/var/app/current/node_modules/step/lib/step.js:39
        throw arguments[0];
        ^

TypeError: Cannot read property 'toString' of undefined
    at Object.module.exports.setupRepo (/var/app/current/node_modules/strider-bitbucket/lib/webapp.js:119:41)
    at Function.createProjectWithKey (/var/app/current/lib/routes/api/repo.js:219:12)
    at next (/var/app/current/node_modules/step/lib/step.js:51:23)
    at next (/var/app/current/node_modules/step/lib/step.js:63:7)
    at ChildProcess.<anonymous> (/var/app/current/node_modules/ssh-keypair/index.js:52:31)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
2299 died 1 null
2379 forked
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

**Comment by svenvarkel** [comment]
It was my bad - the error occurred because there was too little space on the disk. However - if you see cryptic errors like that then check your free space as a first thing. I also tried to upgrade plugins and then another error occurred which lead me to findings that disk space is low. It's not that common to check disk space in AWS ElasticBeanstalk environment... :)
