### ISSUE TITLE
Possible access of undefined variable 

### ISSUE THREAD

**Issue by svenvarkel** [Strider-CD/strider-bitbucket#33]
2016-05-06T10:59:13.042Z - error: TypeError: Cannot read property 'raw_node' of undefined
    at Object.onCommit (/var/app/current/node_modules/strider-bitbucket/lib/webapp.js:297:49)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/app/current/node_modules/express/lib/router/route.js:131:13)
    at projectProvider (/var/app/current/lib/middleware.js:120:3)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/app/current/node_modules/express/lib/router/route.js:131:13)
    at Promise.<anonymous> (/var/app/current/lib/middleware.js:239:7)
    at Promise.<anonymous> (/var/app/current/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at emitOne (events.js:77:13)
    at Promise.emit (events.js:169:7)
    at Promise.emit (/var/app/current/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/var/app/current/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at Promise.resolve (/var/app/current/node_modules/mongoose/lib/promise.js:114:23)
    at Promise.<anonymous> (/var/app/current/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at emitOne (events.js:77:13)
    at Promise.emit (events.js:169:7)

**Comment by svenvarkel** [comment]
This issue relates to #17 because it all starts when the commit list is empty. However better checks for undef variables should be added anyway.

**Comment by knownasilya** [comment]
@svenvarkel PR is very welcome
