### ISSUE TITLE
Canceling a hang test doesn't work

### ISSUE THREAD

**Issue by idanelgar** [Strider-CD/strider-bitbucket#45]
Canceling a hang test doesn't work:
```
0|strider  | 2016-12-22T16:45:02.620Z - info: Got a request to cancel 585bffde1ce93567517b6183
0|strider  | 2016-12-22T16:45:02.635Z - error: TypeError: Cannot read property 'err' of undefined
0|strider  |     at resultCommentor (/usr/lib/node_modules/strider/node_modules/strider-bitbucket/lib/api.js:309:27)
0|strider  |     at EventEmitter.listener (/usr/lib/node_modules/strider/node_modules/strider-bitbucket/lib/api.js:299:5)
0|strider  |     at emitOne (events.js:101:20)
0|strider  |     at EventEmitter.emit (events.js:188:7)
0|strider  |     at EventEmitter.<anonymous> (/usr/lib/node_modules/strider/node_modules/strider-simple-runner/lib/index.js:165:20)
0|strider  |     at EventEmitter.emit (/usr/lib/node_modules/strider/node_modules/eventemitter2/lib/eventemitter2.js:348:22)
0|strider  |     at Object.cancel (/usr/lib/node_modules/strider/node_modules/strider-runner-core/lib/job.js:113:22)
0|strider  |     at EventEmitter.<anonymous> (/usr/lib/node_modules/strider/node_modules/strider-runner-core/lib/job.js:134:14)
0|strider  |     at EventEmitter.emit (/usr/lib/node_modules/strider/node_modules/eventemitter2/lib/eventemitter2.js:348:22)
0|strider  |     at Object.cancelJob (/usr/lib/node_modules/strider/node_modules/strider-simple-runner/lib/index.js:208:13)
0|strider  |     at emitOne (events.js:96:13)
0|strider  |     at EventEmitter.emit (events.js:188:7)
0|strider  |     at /usr/lib/node_modules/strider/lib/utils/user-socket.js:146:28
0|strider  |     at /usr/lib/node_modules/strider/node_modules/mongoose/lib/query.js:2313:18
0|strider  |     at tryCatcher (/usr/lib/node_modules/strider/node_modules/bluebird/js/release/util.js:16:23)
0|strider  |     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/strider/node_modules/bluebird/js/release/promise.js:510:31)
0|strider  |     at Promise._settlePromise (/usr/lib/node_modules/strider/node_modules/bluebird/js/release/promise.js:567:18)
0|strider  |     at Promise._settlePromise0 (/usr/lib/node_modules/strider/node_modules/bluebird/js/release/promise.js:612:10)
0|strider  |     at Promise._settlePromises (/usr/lib/node_modules/strider/node_modules/bluebird/js/release/promise.js:691:18)
0|strider  |     at Async._drainQueue (/usr/lib/node_modules/strider/node_modules/bluebird/js/release/async.js:138:16)
0|strider  |     at Async._drainQueues (/usr/lib/node_modules/strider/node_modules/bluebird/js/release/async.js:148:10)
0|strider  |     at Immediate.Async.drainQueues (/usr/lib/node_modules/strider/node_modules/bluebird/js/release/async.js:17:14)
0|strider  |     at runCallback (timers.js:637:20)
0|strider  |     at tryOnImmediate (timers.js:610:5)
0|strider  |     at processImmediate [as _immediateCallback] (timers.js:582:5)

```

**Comment by knownasilya** [comment]
Thanks for the report.
