### ISSUE TITLE
Can't configure project with BitBucket

### ISSUE THREAD

**Issue by ediblemanager** [Strider-CD/strider-bitbucket#48]
Clicking the button to link with a bitbucket account provides the first page (the authorisation for linking to BB), but on clicking "Grant access", I get the following:

```

Connect
500 Error: Failed to fetch user profile

       at /data/node_modules/passport-bitbucket/lib/strategy.js:89:21
       at passBackControl (/data/node_modules/oauth/lib/oauth.js:397:13)
       at IncomingMessage.<anonymous> (/data/node_modules/oauth/lib/oauth.js:409:9)
       at IncomingMessage.emit (events.js:194:15)
       at endReadableNT (_stream_readable.js:1107:12)
       at process.internalTickCallback (internal/process/next_tick.js:72:19)

```

`SERVER_NAME` is set. Running `striderCD` inside a `docker` container.

**Comment by ediblemanager** [comment]
Fixed: the version of MongoDB I was running was too recent. Reverting to `3.4` seemed to do the trick, along with making sure I wasn't already logged in to BitBucket before trying to link.
